### ISSUE TITLE
感觉不够成熟

### ISSUE THREAD

**Issue by quan01994** [mafly/Mail#1]
最好能用一个邮件队列，所有邮件发送都加到这个队列中，队列的话最好用文本文件去实现。参考 Equeue
最好能有一个发送失败的次数，比如5次，发生失败5次后就不必再发了，然后加入日志。
最好能有一个发送成功和发送失败的表，或者文本，如果用表，那就会依赖数据库，最好用文本。
最好能有一个初始化的方法来设置使用者的信息，比如邮件的host,port,userName等等。

**Comment by mafly** [comment]
你的建议非常棒。这个项目本来定位是一个小工具类，是想让 .Net 开发者几乎不需要再写代码就能快速的完成  发送邮件 这个功能，你所说的队列、失败重发、日志记录、数据持久化这些功能的确是实际项目中必须的，这里没加入这些功能也是因为想着尽量不写库、不用消息队列、不涉及到任何业务逻辑，使用者可以根据自己的功能扩展（哈哈，主要是我懒）。还有初始化方法设置使用者信息这个写在代码中个人认为不如配置在配置文件中，所以 Host 、Port 这些信息实在配置文件中。
不知道上面我表达的是否清楚，其实是可以往完善的方面的做的，把发邮件这个小功能做到在开发中极致的体验，希望大家代码写起来更爽。
